### ISSUE TITLE
A vim configuration for epitech (Already coded)

### ISSUE THREAD

**Issue by HelifeWasTaken** [Epitech/dump#17]
I made a [vim-epitech](https://github.com/Heliferepo/vim-epitech) repository and I was wondering if this plugin could become part of epitech's actual dump (or of epitech's 2022 dump) as vim is installed on it is but not configured

```vim
" Identation settings
set tabstop=4
set shiftwidth=4
set expandtab
set ai
set si

" Set unix format for carriage returns
set fileformat=unix

" Generals bindings
nnoremap <C-c><C-h> :EpiHeader<CR>
nnoremap <C-c><C-c> :w <bar> Compile<CR>
nnoremap <C-g> :GotoLine<CR>
```
This is a sample of the configuration of course the Header are using year time and the epitech header supports :
 ```
c, cpp, make, java, latex, html, lisp, css,
pov, pascal, haskell, vim, sh, bash,
zsh, php, perl, python, ruby, node
```
## Installation
- To install, run `./install.sh`

## Installation (but in the dump)

A sample of what could be put in the `install_packages_dump.sh` file of the dump:

```sh
install_vim_epitech() {
    git clone https://github.com/Heliferepo/vim-epitech
    cd vim-epitech
    git checkout ec936f2a49ca673901d56598e141932fd309ddac
    chmod +x ./install.sh && ./install.sh
    cd .. && rm -rf vim-epitech
}
```
## Thanks

Thanks to : [nasso](https://github.com/nasso) and [Le-Bit](https://github.com/Le-Bit) for making this possible implicitly or not

**Comment by Sadikum** [comment]
Hi! Thank you for your support! I'm interested to use it but in order to do so we need to fork the vim-epitech repository inside the Epitech organisation and use this one (mainly for security reasons). Are you ok with that?

**Comment by HelifeWasTaken** [comment]
Absolutely I have no problem at all about that !
