### ISSUE TITLE
Hidden option on blih

### ISSUE THREAD

**Issue by AlexisAuriac** [Epitech/dump#2]
I noticed the delete option on repository isn't listed in the usage but is coded and works.
Some interesting lines:
- line 117: Definition of the repo_delete function
- line 160: Definition of the usage_repository function
- line 193: Condition to call the repo_delete function

**Comment by Xephi** [comment]
Hello, can you provide a pull request to fix these problems ?

Please read : https://github.com/Epitech/dump/blob/master/CONTRIBUTING.md before open the PR

Thanks for the report anyway

**Comment by Xephi** [comment]
See #3
