### ISSUE TITLE
[ERROR] - Dump script not working for 24.04 due to missing package in "Noble" repo

### ISSUE THREAD

**Issue by TheCodeArchivist** [Epitech/dump#30]
## Prerequisites

* [x] I check that an issue does not already exists for the error I spotted.
* [x] I can not debug and fix that error by myself through a pull request.

## Error's location

The error concerns the file(s) named **install_packages_dump.sh**

The error is present on:

- [ ] intra.epitech.digital (Gandalf) 
- [ ] gandalf.epitech.eu (Merlin)
- [ ] intra.epitech.eu (Intra)
- [ ] jenkins.epitest.eu (Moulinette)
- [x] github.com

## Error's description

_Context: The script mentioned above was ran on a fresh and standard Ubuntu 24.04 install (A.k.a No extra packages other than the basics supplied in the installer by default are installed). On a side note, the machine is also dual booted._

Inside the "install_packages_dump.sh" file, the "libc6-prof" package is apparently mentioned, however when running the installer script, the following is returned:

```
INSTALLING PACKAGES FOR EPITECH'S DUMP
Ubuntu 24.04.1 LTS \n \l
Press ENTER to continue...

Adding component(s) 'universe' to all repositories.
Enabling deb-src for all repositories.
Warning: The unit file, source configuration file or drop-ins of apt-news.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Warning: The unit file, source configuration file or drop-ins of esm-cache.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Hit:1 http://security.ubuntu.com/ubuntu noble-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu noble InRelease
Get:3 http://archive.ubuntu.com/ubuntu noble-updates InRelease [126 kB]
Hit:4 http://archive.ubuntu.com/ubuntu noble-backports InRelease
Fetched 126 kB in 2s (82.1 kB/s)
Reading package lists... Done
Warning: The unit file, source configuration file or drop-ins of apt-news.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Warning: The unit file, source configuration file or drop-ins of esm-cache.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Hit:1 http://archive.ubuntu.com/ubuntu noble InRelease
Hit:2 http://archive.ubuntu.com/ubuntu noble-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu noble-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu noble-security InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
2 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following upgrades have been deferred due to phasing:
  ubuntu-pro-client ubuntu-pro-client-l10n
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'libirrlicht1.8t64' instead of 'libirrlicht1.8'
E: Unable to locate package libc6-prof
snap "teams-for-linux" is already installed, see 'snap help refresh'
./install_packages_dump.sh: line 161: npm: command not found
./install_packages_dump.sh: line 164: curl: command not found
tar: criterion-2.4.2.tar.xz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
cp: cannot stat 'criterion-2.4.2/*': No such file or directory
./install_packages_dump.sh: line 179: git: command not found
./install_packages_dump.sh: line 180: cd: epitech-emacs: No such file or directory
./install_packages_dump.sh: line 181: git: command not found
./install_packages_dump.sh: line 182: ./INSTALL.sh: No such file or directory
./install_packages_dump.sh: line 186: git: command not found
./install_packages_dump.sh: line 187: cd: vim-epitech: No such file or directory
./install_packages_dump.sh: line 188: git: command not found
./install_packages_dump.sh: line 189: ./install.sh: No such file or directory
```

The setup fails, however the most important is the following:
`E: Unable to locate package libc6-prof`
From what I can interpret, the **libc6-prof package cannot be found by apt in the Ubuntu 24.04 "Noble" package repository**, which forces apt to abort the current task, and jeopardize most of the other configuration steps for emacs and vim. 

I also checked on Ubuntu's launchpad to see if libc6-prof was registered as an actual package for 24.04, after verification it does not exist on the list.
https://launchpad.net/ubuntu/noble/+search?text=libc6-prof
_Note: Searching the names of some other packages on the list within the installer script returned an actual entry, so the website seems to be giving proper info on what is and isn't supported in the current Ubuntu 24.04 "Noble" repo._  

## Error's correction

Unknowing if libc6-prof is crucial or not to certain coding tasks we'll be partaking during the curriculum, _I will likely be wrong about the fixes I'm about to suggest_:
* One fix would be to remove the libc6-prof package if it's deprecated for more up-to-date and available packages, and replace it with the latter if possible.
* If the first fix cannot be achieved, an action could be taken to update the README.md file to notify future users that Ubuntu 24.04 is **currently not supported** to use with the dump's required tool-set, and therefore should be avoided in favor of supported versions.

## Additional contact information
In the case you need to reach me, feel free to at the following email address:
liam.colle@epitech.eu
_(My teams is also open)_

**Comment by emneo-dev** [comment]
@TheCodeArchivist You might want to use the new script that has been created or just follow the new instructions in the README.
All the packages are now packed in a PPA (I wouldn't consider that ideal but it works).

**Comment by TheCodeArchivist** [comment]
@emneo-dev 
Thanks for reaching back.
I'll be using the updated procedures once we obtain the official dump USBs.

Have a good day.
