### ISSUE TITLE
[Arcade Project Libraries] Maybe it's an idea to add all the libraries specified in the subject?

### ISSUE THREAD

**Issue by Xephi** [Epitech/dump#5]
Maybe it's an idea to add all the libraries specified in the subject?

![image](https://user-images.githubusercontent.com/6763873/54652328-d1732b80-4ab6-11e9-845e-aa24bd33a18e.png)

_Originally posted by @IamBlueSlime in https://github.com/Epitech/dump/pull/4#issuecomment-474646531_

**Comment by Xephi** [comment]
@Sadikum Idk if we have to, btw, it's your own decision :D

**Comment by Sadikum** [comment]
No need for now. For next year, we will shorten the list and specify the versions.
